-- migration: create kanji quiz schema
-- purpose: define enums, tables, constraints, indexes, rls policies for kanji quiz
-- affected objects: types jlpt_level, question_type, quiz_type, quiz_status; tables kanji, quiz, quiz_questions, need_reviews; indexes listed below
-- special considerations: references auth.users; kanji is public read-only with explicit deny on writes

-- 1) enum types for jlpt level, quiz structure, and status
create type jlpt_level as enum ('N5', 'N4', 'N3', 'N2', 'N1');
create type question_type as enum ('reading', 'meaning');
create type quiz_type as enum ('level', 'need_review');
create type quiz_status as enum ('in_progress', 'completed', 'abandoned');

-- 2) kanji master data (public read-only)
create table kanji (
  id integer generated by default as identity primary key,
  character char(1) not null,
  level jlpt_level not null,
  readings jsonb not null,
  meanings jsonb not null,
  created_at timestamptz not null default now()
);

-- index to speed level-filtered queries
create index kanji_level_idx on kanji(level);

-- rls is required even for public data
alter table kanji enable row level security;

-- kanji select: public read-only
create policy kanji_select_anon
  on kanji
  for select
  to anon
  using (true);

create policy kanji_select_authenticated
  on kanji
  for select
  to authenticated
  using (true);

-- kanji writes are explicitly denied for both anon and authenticated roles
create policy kanji_insert_anon
  on kanji
  for insert
  to anon
  with check (false);

create policy kanji_insert_authenticated
  on kanji
  for insert
  to authenticated
  with check (false);

create policy kanji_update_anon
  on kanji
  for update
  to anon
  using (false)
  with check (false);

create policy kanji_update_authenticated
  on kanji
  for update
  to authenticated
  using (false)
  with check (false);

create policy kanji_delete_anon
  on kanji
  for delete
  to anon
  using (false);

create policy kanji_delete_authenticated
  on kanji
  for delete
  to authenticated
  using (false);

-- 3) quiz sessions
create table quiz (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  type quiz_type not null,
  level jlpt_level,
  question_count smallint not null,
  status quiz_status not null default 'in_progress',
  score_percent numeric(5, 2),
  created_at timestamptz not null default now(),
  completed_at timestamptz,
  constraint quiz_question_count_check check (question_count > 0),
  constraint quiz_type_level_check check (
    (type = 'level' and level is not null) or
    (type = 'need_review' and level is null)
  ),
  constraint quiz_completed_at_check check ((status = 'completed') = (completed_at is not null))
);

-- index to list quizzes per user quickly
create index quiz_user_created_idx on quiz(user_id, created_at desc);

alter table quiz enable row level security;

-- quiz access for anon is denied
create policy quiz_select_anon
  on quiz
  for select
  to anon
  using (false);

create policy quiz_insert_anon
  on quiz
  for insert
  to anon
  with check (false);

create policy quiz_update_anon
  on quiz
  for update
  to anon
  using (false)
  with check (false);

create policy quiz_delete_anon
  on quiz
  for delete
  to anon
  using (false);

-- quiz access for authenticated users is scoped to their own rows
create policy quiz_select_authenticated
  on quiz
  for select
  to authenticated
  using (user_id = auth.uid());

create policy quiz_insert_authenticated
  on quiz
  for insert
  to authenticated
  with check (user_id = auth.uid());

create policy quiz_update_authenticated
  on quiz
  for update
  to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

create policy quiz_delete_authenticated
  on quiz
  for delete
  to authenticated
  using (user_id = auth.uid());

-- 4) quiz questions
create table quiz_questions (
  id bigint generated by default as identity primary key,
  quiz_id bigint not null references quiz(id) on delete cascade,
  kanji_id integer not null references kanji(id),
  sequence smallint not null,
  question_type question_type not null,
  user_answer text,
  answered_at timestamptz,
  is_correct boolean,
  created_at timestamptz not null default now(),
  constraint quiz_questions_sequence_unique unique (quiz_id, sequence),
  constraint quiz_questions_kanji_question_unique unique (quiz_id, kanji_id, question_type),
  constraint quiz_questions_answered_check check ((answered_at is not null) = (user_answer is not null))
);

-- indexes to speed quiz and kanji lookups
create index quiz_questions_idx on quiz_questions(quiz_id);
create index quiz_questions_kanji_idx on quiz_questions(kanji_id);

alter table quiz_questions enable row level security;

-- quiz_questions access for anon is denied
create policy quiz_questions_select_anon
  on quiz_questions
  for select
  to anon
  using (false);

create policy quiz_questions_insert_anon
  on quiz_questions
  for insert
  to anon
  with check (false);

create policy quiz_questions_update_anon
  on quiz_questions
  for update
  to anon
  using (false)
  with check (false);

create policy quiz_questions_delete_anon
  on quiz_questions
  for delete
  to anon
  using (false);

-- quiz_questions access for authenticated users is scoped through the owning quiz
create policy quiz_questions_select_authenticated
  on quiz_questions
  for select
  to authenticated
  using (
    exists (
      select 1
      from quiz q
      where q.id = quiz_questions.quiz_id
        and q.user_id = auth.uid()
    )
  );

create policy quiz_questions_insert_authenticated
  on quiz_questions
  for insert
  to authenticated
  with check (
    exists (
      select 1
      from quiz q
      where q.id = quiz_questions.quiz_id
        and q.user_id = auth.uid()
    )
  );

create policy quiz_questions_update_authenticated
  on quiz_questions
  for update
  to authenticated
  using (
    exists (
      select 1
      from quiz q
      where q.id = quiz_questions.quiz_id
        and q.user_id = auth.uid()
    )
  )
  with check (
    exists (
      select 1
      from quiz q
      where q.id = quiz_questions.quiz_id
        and q.user_id = auth.uid()
    )
  );

create policy quiz_questions_delete_authenticated
  on quiz_questions
  for delete
  to authenticated
  using (
    exists (
      select 1
      from quiz q
      where q.id = quiz_questions.quiz_id
        and q.user_id = auth.uid()
    )
  );

-- 5) need_reviews: per-user kanji review list
create table need_reviews (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  kanji_id integer not null references kanji(id),
  created_at timestamptz not null default now(),
  constraint need_reviews_user_kanji_unique unique (user_id, kanji_id)
);

alter table need_reviews enable row level security;

-- need_reviews access for anon is denied
create policy need_reviews_select_anon
  on need_reviews
  for select
  to anon
  using (false);

create policy need_reviews_insert_anon
  on need_reviews
  for insert
  to anon
  with check (false);

create policy need_reviews_update_anon
  on need_reviews
  for update
  to anon
  using (false)
  with check (false);

create policy need_reviews_delete_anon
  on need_reviews
  for delete
  to anon
  using (false);

-- need_reviews access for authenticated users is scoped to their own rows
create policy need_reviews_select_authenticated
  on need_reviews
  for select
  to authenticated
  using (user_id = auth.uid());

create policy need_reviews_insert_authenticated
  on need_reviews
  for insert
  to authenticated
  with check (user_id = auth.uid());

create policy need_reviews_update_authenticated
  on need_reviews
  for update
  to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

create policy need_reviews_delete_authenticated
  on need_reviews
  for delete
  to authenticated
  using (user_id = auth.uid());
